routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'/admin'],function(){
    Route::get('/login','AdminLoginController@login');
    Route::post('/login','AdminLoginController@verify')->name('admins.verify');
    Route::get('/register','AdminLoginController@register')->name('admins.register');
    Route::post('/register','AdminLoginController@store')->name('admins.store');
    Route::get('/logout',function(){
        session()->forget('USER_EMAIL');
        return redirect('/admin/login');
    });

});


Route::group(['middleware'=>['admin']],function(){
    Route::resource('/admin/books','BookController');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    protected $table = 'tbl_books';
    protected $fillable =['title','author_name','published_date','created_at','updated_at'];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;

class BookController extends Controller
{

    public function index()
    {
       return view('books.index')->with('books',Book::all());
    }


    public function create()
    {
        return view('books.create');
    }


    public function store(Request $request)
    {
        $book = new Book();
        $book->title = $request->title;
        $book->author_name = $request->author_name;
        $book->published_date = $request->published_date;
        // $book->title = $request->title;
        // $book->title = $request->title;
        $book->save();
        $request->session()->flash('msg','Data inserted Successfully');
        return redirect('/admin/books');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $book = Book::find($id);
        return view('books.edit')->with('book',$book);
    }


    public function update(Request $request, $id)
    {
        $book = Book::find($id);
        $book->title = $request->title;
        $book->author_name = $request->author_name;
        $book->published_date = $request->published_date;
        // $book->title = $request->title;
        // $book->title = $request->title;
        $book->save();
        $request->session()->flash('msg','Data Updated Successfully');
        return redirect('/admin/books');
    }

    public function destroy(Request $request, $id)
    {
        $book = new Book();
        $book->destroy($id);
        $request->session()->flash('msg','Data Deleted Successfully');
        return redirect('/admin/books');

    }
}

resources/views/books/create.blade.php
@extends('layouts.master');

@section('content')
<div class="container">
<div class="pull-right">
    <a href="{{url('/admin/books')}}" class="btn btn-success">View Books</a>
</div>
<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Quick Example</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" action="{{route('books.store')}}">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="Enter Title">
                </div>
                <div class="form-group">
                    <label for="author_name">Author Name</label>
                    <input type="text" class="form-control" name="author_name" id="author_name"
                        placeholder="Enter Author Title">
                </div>
                <div class="form-group">
                    <label for="published_date">File input</label>
                    <input type="date" name="published_date" id="published_date" class="form-control">
                </div>



              <button type="submit" class="btn btn-primary">Submit</button>
              <a href="#" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
<!-- /.card -->

<!-- general form elements -->
</div>
</div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.master');

@section('content')
<div class="pull-right">
    <a href="{{url('/admin/books')}}" class="btn btn-success">View Books</a>
</div>
<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Quick Example</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post" action="{{route('books.update', $book->id)}}">
            @csrf @method('put')
            <div class="card-body">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" value="{{$book->title}}" name="title" id="title" placeholder="Enter Title">
                </div>
                <div class="form-group">
                    <label for="author_name">Author Name</label>
                    <input type="text" class="form-control" value="{{$book->author_name}}" name="author_name" id="author_name"
                        placeholder="Enter Author Title">
                </div>
                <div class="form-group">
                    <label for="published_date">File input</label>
                    <input type="date" name="published_date" value="{{$book->published_date}}" id="published_date" class="form-control">
                </div>



              <button type="submit" class="btn btn-primary">Submit</button>
              <a href="#" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
<!-- /.card -->

<!-- general form elements -->
</div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.master')
@section('content')
@if(Session::has('msg'))
<div class="alert alert-success text-center style="align-center" >
    {{session('msg')}}
</div>
@endif

<div class="container" style="margin-top:30px">
            <div class="col-auto float-right ml-auto">
                <a href="{{route('books.create')}}" class='btn btn-primary'>Add Books</a>
            </div>
            <div class="container">
                <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Available Books</h3>

                    <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                            <i class="fas fa-search"></i>
                        </button>
                        </div>
                    </div>
                    </div>
                </div>
                <!-- /.card-header -->
{{-- {{session()->all();}} --}}


                {{-- {{session()->all();}} --}}

                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Author Name</th>
                        <th>Published_date</th>
                        <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($books as $book)
                        <tr>
                        <td>{{$loop->index+1}}</td>
                        <td>{{$book->title}}</td>
                        <td>{{$book->author_name}}</td>
                        <td>{{$book->published_date}}</td>
                        <td>
                            <form action="{{route('books.destroy',$book->id)}}" method="post">
                                @csrf @method('delete')
                            <a href="{{route('books.edit',$book->id)}}" class="btn btn-warning btn-xs"><i class="fa fa-pencil-alt"></i></a>
                            <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>


                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
@endsection